version: "3.8"
services:
  db:
    container_name: programmingecto-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: music_db
      POSTGRES_PASSWORD: ${MUSIC_DB_PASSWORD}
      POSTGRES_DB: music_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: programmingecto-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"